export const GET_ALL_COUNTRIES_LISTED = "GET_ALL_COUNTRIES_LISTED";
export const GET_LATEST_TOTALS = "GET_LATEST_TOTALS";
export const GET_LATEST_COUNTRY_NAME = "GET_LATEST_COUNTRY_NAME";
export const SET_GLOBAL_DATA = "SET_GLOBAL_DATA";
export const GET_PAKISTAN_ALL_DATA = "GET_PAKISTAN_ALL_DATA";
